[package]
name = "abex-core"
version = "1.1.1"
published-at = "0xe625f9b22467751d9adccdb53f12faa64dbebb5343d2f9f52849b012d55809f5"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "mainnet-v1.13.2"
override = true

[dependencies.Pyth]
local = "../vendor/pyth"

[dependencies.PythV1]
local = "../vendor/pyth-v1"

[addresses]
std = "0x1"
sui = "0x2"
pyth = "0x00b53b0f4174108627fbee72e2498b58d6a2714cded53fac537034c220d26302"
pyth_v1 = "0x8d97f1cd6ac663735be08d1d2b6d02a159e711586461306ce60a2b7a6a565a9e"
abex_core = "0x0"
