[package]
name = "abex-ada"
version = "0.0.1"
published-at = "0xabc"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "sui-v1.1.1"

[addresses]
abex_ada = "0xabc"
std = "0x1"
sui = "0x2"
